openapi: 3.1.0
info:
  title: Task Management API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/v1
    description: Local development
  - url: https://api.yoursite.com/api/v1
    description: Production
paths:
  /auth/register:
    post:
      summary: Register a new user
      description: This endpoint creates a user.
      operationId: registerUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '409':
          description: The email provided is already in use.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: The email provided is already in use.
        '422':
          description: The request does not follow the body pattern or some field does not follow some constraint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Your request does not follow the body pattern or some field does not follow some constraint.
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/login:
    post:
      summary: Log in to the application
      description: This endpoint authenticates the user and returns access credentials.
      operationId: loginUser
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticateUserRequest'
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticateUserResponse'
        '202':
          description: 2FA required. Temporary token sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  authToken:
                    type: string
                    description: Temporary token for 2FA verification
        '401':
          description: Invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid credentials.
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found.
        '422':
          description: The request does not follow the body pattern or some field does not follow some constraint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Your request does not follow the body pattern or some field does not follow some constraint.
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/refresh-access-token:
    post:
      summary: Refresh access token
      description: Generates a new access token using a valid refresh token provided via the `refreshToken` cookie.
      tags:
        - Auth
      parameters:
        - in: cookie
          name: refreshToken
          required: true
          schema:
            type: string
          description: Refresh token (JWT) provided in cookie.
      responses:
        '200':
          description: New access token generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  newAccessToken:
                    type: string
                    description: JWT access token to use in authenticated endpoints
        '400':
          description: refreshToken missing (cookie)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: refreshToken missing (cookie)
        '401':
          description: Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                TokenExpiredError:
                  value:
                    message: Invalid or expired authentication token.
                JsonWebTokenError:
                  value:
                    message: Invalid or expired authentication token.
                NotBeforeError:
                  value:
                    message: Invalid or expired authentication token.
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/2fa/enable:
    post:
      summary: Generate 2FA QR Code for the authenticated user
      description: |
        Returns a PNG image with the QR Code for two-factor authentication setup.
        Requires authentication (JWT Bearer Token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: QR code image generated successfully
          content:
            image/png:
              schema:
                type: string
                format: binary
        '409':
          description: 2FA is already enabled for this user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: 2FA is already active.
        '500':
          description: An error occurred during QR Code generation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: An error occurred during QR Code generation.
  /auth/2fa/setup/verify:
    post:
      summary: Validate 2FA code during setup
      description: |
        Confirms the 2FA setup by validating the code sent by the user.  
        Requires authentication (JWT Bearer Token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultipleFactorAuthDto'
      responses:
        '204':
          description: Valid code. 2FA enabled successfully.
        '400':
          description: The code is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: The code is invalid.
        '404':
          description: Secret not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Secret not found.
        '422':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /auth/2fa/verify:
    post:
      summary: Authenticate user via 2FA after login
      description: |
        Receives a 2FA code, validates it, and returns an accessToken in response and sets a refreshToken as a cookie.  
        The user must be partially authenticated (temporary authentication token).
      tags:
        - Auth
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultipleFactorAuthDto'
      responses:
        '200':
          description: 2FA authentication successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT to use for authenticated endpoints
        '400':
          description: The code is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: The code is invalid.
        '404':
          description: Secret not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Secret not found.
        '422':
          description: Invalid request payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /user:
    get:
      summary: Get logged user information
      description: Returns the profile information of the authenticated user.
      operationId: getUserProfile
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found.
        '500':
          description: Unknown Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Unknown Error.
  /task:
    get:
      summary: Get all tasks for the authenticated user
      tags:
        - Task
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of the user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid or expired authentication token.
    post:
      summary: Create a new task
      tags:
        - Task
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTask'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Your request does not follow the body pattern or some field does not follow some constraint.
  /task/{taskId}:
    get:
      summary: Get a task by its ID (for authenticated user)
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
          description: Task ID
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: The parameter taskId must be numeric.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: taskId param must be numeric.
        '401':
          description: Invalid or expired authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Invalid or expired authentication token.
    put:
      summary: Update all properties of a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTask'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '422':
          description: Invalid parameters or request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Your request does not follow the body pattern or some field does not follow some constraint.
    patch:
      summary: Update only the status (isDone) of a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeTaskStatus'
      responses:
        '204':
          description: Task status updated successfully
        '422':
          description: The request does not follow the body pattern or some field does not follow some constraint.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Your request does not follow the body pattern or some field does not follow some constraint.
    delete:
      summary: Delete a task
      tags:
        - Task
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: taskId
          schema:
            type: integer
          required: true
      responses:
        '204':
          description: Task deleted
        '400':
          description: The parameter taskId must be numeric.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: taskId param must be numeric.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: User name (required)
        age:
          type: integer
          minimum: 1
          description: User age (required)
        email:
          type: string
          maxLength: 255
          format: email
          description: User email (required)
        password:
          type: string
          description: User password (required)
        twoFactorEnabled:
          type: boolean
          default: false
          description: Enable two-factor authentication (optional, defaults to false)
      required:
        - name
        - age
        - email
        - password
    CreateUserResponse:
      type: object
      properties:
        userId:
          type: integer
          description: User ID
        userName:
          type: string
          description: Name of the user
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error description
      required:
        - message
    AuthenticateUserRequest:
      type: object
      properties:
        email:
          type: string
          maxLength: 255
          format: email
          description: Email address (required)
        password:
          type: string
          description: User password (required)
      required:
        - email
        - password
    AuthenticateUserResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token to use for authenticated endpoints
        is2faRequired:
          type: boolean
          description: Indicates if 2FA is required for this user
        authToken:
          type: string
          description: Temporary token for 2FA flow (if applicable)
    MultipleFactorAuthDto:
      type: object
      properties:
        code:
          type: string
          description: 6-digit code sent by the user
          minLength: 6
          maxLength: 6
      required:
        - code
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        twoFactorEnabled:
          type: boolean
          description: Indicates if two-factor authentication is enabled for the user
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
          nullable: true
        dueDate:
          type: string
          format: date
          nullable: true
        isDone:
          type: boolean
        owner:
          type: integer
    CreateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        isDone:
          type: boolean
          default: false
      required:
        - title
    UpdateTask:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        isDone:
          type: boolean
        owner:
          type: integer
    ChangeTaskStatus:
      type: object
      properties:
        isDone:
          type: boolean
      required:
        - isDone
